export interface Skill {
  label: string
}

// Add more skills or find an API to use instead
export const skillsData: Skill[] = [
  { label: "Agile Development" },
  { label: "Algorithms" },
  { label: "API Design" },
  { label: "Apache" },
  { label: "Artificial Intelligence" },
  { label: "ASP.NET" },
  { label: "AWS" },
  { label: "Azure" },
  { label: "Bash" },
  { label: "Big Data" },
  { label: "Blockchain" },
  { label: "C" },
  { label: "C#" },
  { label: "CSS" },
  { label: "Data Analysis" },
  { label: "Data Structures" },
  { label: "Database Design" },
  { label: "Django" },
  { label: "Docker" },
  { label: "Electron" },
  { label: "Elixir" },
  { label: "Elm" },
  { label: "Express.js" },
  { label: "Flask" },
  { label: "Git" },
  { label: "Go" },
  { label: "GraphQL" },
  { label: "Hadoop" },
  { label: "Haskell" },
  { label: "HTML" },
  { label: "iOS Development" },
  { label: "Java" },
  { label: "JavaScript" },
  { label: "jQuery" },
  { label: "Kotlin" },
  { label: "Lambda" },
  { label: "Linux" },
  { label: "Machine Learning" },
  { label: "MongoDB" },
  { label: "MySQL" },
  { label: "Neo4j" },
  { label: "Nginx" },
  { label: "Node.js" },
  { label: "Objective-C" },
  { label: "Ocaml" },
  { label: "OpenCV" },
  { label: "Pandas" },
  { label: "PostgreSQL" },
  { label: "PowerShell" },
  { label: "Python" },
  { label: "R" },
  { label: "React" },
  { label: "Redis" },
  { label: "Regex" },
  { label: "Ruby" },
  { label: "Ruby on Rails" },
  { label: "Rust" },
  { label: "Sass" },
  { label: "Scala" },
  { label: "Shell" },
  { label: "SQL" },
  { label: "SQL Server" },
  { label: "Swift" },
  { label: "TensorFlow" },
  { label: "TypeScript" },
  { label: "Unity" },
  { label: "Vim" },
  { label: "Vue.js" },
  { label: "Windows" },
  { label: "WordPress" },
  { label: "Xamarin" },
  { label: "Xcode" },
  { label: "Ansible" },
  { label: "Ansible Tower" },
  { label: "Arduino" },
  { label: "CakePHP" },
  { label: "Cassandra" },
  { label: "Chef" },
  { label: "Cloud Computing" },
  { label: "Couchbase" },
  { label: "Cucumber" },
  { label: "D3.js" },
  { label: "Darknet" },
  { label: "Debian" },
  { label: "Deep Learning" },
  { label: "Drupal" },
  { label: "Embedded Systems" },
  { label: "Ember.js" },
  { label: "Erlang" },
  { label: "F#" },
  { label: "Firebase" },
  { label: "Flutter" },
  { label: "Gatsby" },
  { label: "GitLab" },
  { label: "GoLang" },
  { label: "Google Cloud Platform" },
  { label: "Graph Databases" },
  { label: "Gulp" },
  { label: "Hibernate" },
  { label: "Ionic" },
  { label: "Jasmine" },
  { label: "Java Spring" },
  { label: "Jenkins" },
  { label: "Jest" },
  { label: "Jinja2" },
  { label: "jOOQ" },
  { label: "Julia" },
  { label: "Kafka" },
  { label: "Keras" },
  { label: "Kubernetes" },
  { label: "Laravel" },
  { label: "Linux Kernel" },
  { label: "Lucene" },
  { label: "MapReduce" },
  { label: "Mocha" },
  { label: "Neural Networks" },
  { label: "Nim" },
  { label: "NoSQL" },
  { label: "Next.js" },
  { label: "OOP" },
  { label: "OpenCL" },
  { label: "Perl" },
  { label: "PHP" },
  { label: "Puppet" },
  { label: "RabbitMQ" },
  { label: "Rails" },
  { label: "Redux" },
  { label: "Reinforcement Learning" },
  { label: "S3" },
  { label: "SaltStack" },
  { label: "Scrum" },
  { label: "Selenium" },
  { label: "Serverless" },
  { label: "Spring Boot" },
  { label: "Spyder" },
  { label: "SQLAlchemy" },
  { label: "SwiftUI" },
  { label: "Terraform" },
  { label: "Tomcat" },
  { label: "Travis CI" },
  { label: "Vagrant" },
  { label: "Vault" },
  { label: "Vuex" },
  { label: "Webpack" },
  { label: "XGBoost" },
  { label: "YAML" },
  { label: "Zend Framework" },
  { label: "3D Printing" },
  { label: "Active Directory" },
  { label: "ADO.NET" },
  { label: "ADO.NET Entity Framework" },
  { label: "Ajax" },
  { label: "Altera" },
  { label: "Android Development" },
  { label: "Angular" },
  { label: "AngularJS" },
  { label: "Ansible" },
  { label: "Apache Cordova" },
  { label: "Apache Flink" },
  { label: "Apache Hadoop" },
  { label: "Apache HBase" },
  { label: "Apache Hive" },
  { label: "Apache HttpComponents" },
  { label: "Apache Maven" },
  { label: "Apache Mesos" },
  { label: "Apache Pig" },
  { label: "Apache Spark" },
  { label: "Apache Storm" },
  { label: "Apache Tomcat" },
  { label: "Apache Zookeeper" },
  { label: "Appium" },
  { label: "Apple Xcode" },
  { label: "ArangoDB" },
  { label: "ASP.NET Core" },
  { label: "Atlassian Jira" },
  { label: "Audacity" },
  { label: "Audio Processing" },
  { label: "AutoCAD" },
  { label: "AWS Lambda" },
  { label: "AWS S3" },
  { label: "Babel" },
  { label: "Backbone.js" },
  { label: "Bash Scripting" },
  { label: "Big Data" },
  { label: "Bigtable" },
  { label: "Bokeh" },
  { label: "Bootstrap" },
  { label: "Bottle.py" },
  { label: "Bower" },
  { label: "Browserify" },
  { label: "Bundler" },
  { label: "C# .NET" },
  { label: "C++" },
  { label: "Cadence" },
  { label: "Caffe" },
  { label: "Cassandra" },
  { label: "Chai" },
  { label: "Chef" },
  { label: "Circuit Verification" },
  { label: "Circuit Design" },
  { label: "CLI" },
  { label: "Cloud Foundry" },
  { label: "Cloud Functions" },
  { label: "Cocoa" },
  { label: "CocoaPods" },
  { label: "Cognito" },
  { label: "CouchDB" },
  { label: "CQRS" },
  { label: "Cryptography" },
  { label: "Cucumber" },
  { label: "Cuda" },
  { label: "D3.js" },
  { label: "Dart" },
  { label: "Data Engineering" },
  { label: "Data Fusion" },
  { label: "Data Mining" },
  { label: "Data Science" },
  { label: "Data Structures" },
  { label: "Debian" },
  { label: "Functional programming" }
]
  .filter((v, i, a) => a.findIndex((v2) => v2.label === v.label) === i)
  .sort((a, b) => a.label.localeCompare(b.label))
